server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG
    
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
          

                  